from datetime import datetime, timedelta, timezone
from typing import List, Dict, Any

# Current reference base date: 2026-10-05
BASE_DATE = datetime.now(timezone.utc)

def get_iso_date(offset_days: int) -> str:
    return (BASE_DATE + timedelta(days=offset_days)).strftime("%Y-%m-%dT23:59:59Z")

SAMPLE_OPPORTUNITIES: List[Dict[str, Any]] = [
    {
        "id": "opp-gsoc-2026",
        "title": "Google Summer of Code (GSoC) 2026",
        "organization": "Google Open Source",
        "category": "Internship",
        "description": "Google Summer of Code is a global, online program focused on bringing new contributors into open source software development. Contributors work with an open source organization on a 12+ week programming project under the guidance of mentors.",
        "required_skills": ["Git", "Python", "JavaScript", "Open Source"],
        "preferred_skills": ["Docker", "C++", "Rust", "API Design"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "BCA", "MCA", "M.Tech", "All"],
            "eligible_academic_years": ["1st Year", "2nd Year", "3rd Year", "4th Year", "Masters"],
            "min_cgpa": None,
            "eligible_branches": ["All"],
            "other_requirements": "Open to all students enrolled in an accredited higher education institution or open source newcomers."
        },
        "location": "Global / Remote",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-20),
        "deadline": get_iso_date(3),  # Urgent: 3 days remaining (Red)
        "official_url": "https://summerofcode.withgoogle.com",
        "source_url": "https://opensource.googleblog.com",
        "source_name": "Official Google Open Source Blog",
        "publication_date": get_iso_date(-20),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 98,
        "verification_notes": "Official program confirmed from primary summerofcode.withgoogle.com domain.",
        "opportunity_status": "Closing Soon",
        "stipend_or_reward": "$1,500 - $3,300 Stipend (PPP adjusted)",
        "tags": ["Open Source", "Global", "Mentorship", "High Value"],
        "is_sample": True
    },
    {
        "id": "opp-aws-cloud-intern",
        "title": "Cloud Solutions Architecture Intern",
        "organization": "Amazon Web Services (AWS)",
        "category": "Internship",
        "description": "Join AWS as a Solutions Architect Intern. You will partner with experienced architects to design scalable, secure, and resilient cloud architectures on AWS for leading startups and enterprise customers.",
        "required_skills": ["Python", "Cloud Computing", "SQL", "Networking Basics"],
        "preferred_skills": ["AWS", "Docker", "Linux", "Terraform"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "MCA", "M.Tech"],
            "eligible_academic_years": ["3rd Year", "4th Year"],
            "min_cgpa": 7.0,
            "eligible_branches": ["Computer Science and Engineering", "Information Technology", "Electronics and Communication"],
            "other_requirements": "Graduating in 2026 or 2027. Available for a 6-month full-time internship."
        },
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9279,
        "longitude": 77.6271,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-10),
        "deadline": get_iso_date(8),  # Approaching: 8 days remaining (Yellow)
        "official_url": "https://amazon.jobs",
        "source_url": "https://amazon.jobs/en/jobs/AWS2026",
        "source_name": "Amazon Student Careers Portal",
        "publication_date": get_iso_date(-10),
        "last_verified_date": get_iso_date(-2),
        "verification_status": "Verified Source",
        "trust_score": 96,
        "verification_notes": "Matched official company career portal SSL and domain certificates.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹80,000 / month + Relocation assistance",
        "tags": ["Cloud", "AWS", "High Stipend", "Pre-Placement Offer"],
        "is_sample": True
    },
    {
        "id": "opp-msft-ai-fellowship",
        "title": "Microsoft Research AI & NLP Fellowship 2026",
        "organization": "Microsoft Research India",
        "category": "Fellowship",
        "description": "Microsoft Research India Fellowship is a 1-2 year post-baccalaureate or undergraduate research fellowship program. Fellows work directly with world-renowned scientists in LLMs, Multimodal AI, and Systems.",
        "required_skills": ["Python", "Machine Learning", "PyTorch", "Data Structures"],
        "preferred_skills": ["Natural Language Processing", "Transformers", "Linear Algebra"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "M.Tech", "M.Sc"],
            "eligible_academic_years": ["3rd Year", "4th Year", "Masters"],
            "min_cgpa": 8.0,
            "eligible_branches": ["Computer Science and Engineering", "Data Science", "Mathematics", "All"],
            "other_requirements": "Strong academic record and demonstrable research curiosity or competitive programming achievements."
        },
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9815,
        "longitude": 77.5956,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-15),
        "deadline": get_iso_date(18), # > 14 days: Green
        "official_url": "https://www.microsoft.com/en-us/research/lab/microsoft-research-india/",
        "source_url": "https://careers.microsoft.com",
        "source_name": "Microsoft Research Official Announcements",
        "publication_date": get_iso_date(-15),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Verified verified enterprise source with authentic application link.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹1,20,000 / month + Conference travel grants",
        "tags": ["AI", "Research", "Top Tier", "Fellowship"],
        "is_sample": True
    },
    {
        "id": "opp-sih-2026",
        "title": "Smart India Hackathon (SIH) 2026",
        "organization": "Ministry of Education & AICTE",
        "category": "Hackathon",
        "description": "Smart India Hackathon is a nationwide initiative to provide students a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and problem-solving mindset.",
        "required_skills": ["Problem Solving", "Web Development", "Team Collaboration", "Git"],
        "preferred_skills": ["React", "FastAPI", "Mobile App Development", "IoT"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "BCA", "MCA", "All"],
            "eligible_academic_years": ["1st Year", "2nd Year", "3rd Year", "4th Year", "Masters"],
            "min_cgpa": None,
            "eligible_branches": ["All"],
            "other_requirements": "Teams of 6 students from the same college, with at least one female teammate mandatory."
        },
        "location": "New Delhi, Delhi",
        "city": "New Delhi",
        "country": "India",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "work_mode": "On-site",
        "opening_date": get_iso_date(-25),
        "deadline": get_iso_date(2),  # Urgent: 2 days (Red)
        "official_url": "https://www.sih.gov.in",
        "source_url": "https://www.sih.gov.in/notifications",
        "source_name": "AICTE Innovation Cell",
        "publication_date": get_iso_date(-25),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 100,
        "verification_notes": "Government portal (.gov.in) with active security certificate and verified gazette notification.",
        "opportunity_status": "Closing Soon",
        "stipend_or_reward": "₹1,00,000 per problem statement prize",
        "tags": ["Government", "Hackathon", "Innovation", "National"],
        "is_sample": True
    },
    {
        "id": "opp-reliance-scholarship",
        "title": "Reliance Foundation Undergraduate Scholarship 2026",
        "organization": "Reliance Foundation",
        "category": "Scholarship",
        "description": "Supports meritorious students from across India pursuing undergraduate degree programs in any stream. The scholarship aims to enable talented youth to pursue higher education without financial constraints.",
        "required_skills": ["Academic Excellence", "Leadership", "Communication"],
        "preferred_skills": ["Social Impact", "Community Involvement"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "B.Com", "BA", "All"],
            "eligible_academic_years": ["1st Year", "2nd Year"],
            "min_cgpa": 7.5,
            "eligible_branches": ["All"],
            "other_requirements": "Annual household income less than ₹15 Lakhs (preference to < ₹2.5 Lakhs). Minimum 60% in 12th standard."
        },
        "location": "Pan-India / Remote Application",
        "city": "Mumbai",
        "country": "India",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-30),
        "deadline": get_iso_date(12), # 12 days remaining (Yellow)
        "official_url": "https://www.scholarships.reliancefoundation.org",
        "source_url": "https://www.scholarships.reliancefoundation.org/Eligibility.aspx",
        "source_name": "Reliance Foundation Official Portal",
        "publication_date": get_iso_date(-30),
        "last_verified_date": get_iso_date(-3),
        "verification_status": "Verified Source",
        "trust_score": 97,
        "verification_notes": "Verified CSR non-profit foundation initiative with transparent selection framework.",
        "opportunity_status": "Active",
        "stipend_or_reward": "Up to ₹2,00,000 for degree duration + Mentorship",
        "tags": ["Scholarship", "Financial Aid", "Undergraduate", "Merit-cum-Means"],
        "is_sample": True
    },
    {
        "id": "opp-adobe-wit-scholarship",
        "title": "Adobe India Women-in-Technology Scholarship",
        "organization": "Adobe India",
        "category": "Scholarship",
        "description": "Strives to create more gender equality in the tech industry by encouraging talented female students to excel in computing and technology and become active role models.",
        "required_skills": ["Computer Science Fundamentals", "Data Structures", "Algorithms"],
        "preferred_skills": ["Python", "Java", "Web Technologies", "AI"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "MCA", "M.Tech"],
            "eligible_academic_years": ["3rd Year", "4th Year"],
            "min_cgpa": 8.0,
            "eligible_branches": ["Computer Science and Engineering", "Information Technology", "AI & Data Science"],
            "other_requirements": "Must identify as female. Enrolled in a recognized Indian engineering college."
        },
        "location": "Bengaluru / Noida",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9352,
        "longitude": 77.6943,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-14),
        "deadline": get_iso_date(22), # 22 days remaining (Green)
        "official_url": "https://www.adobe.com/in/careers/university/scholarships.html",
        "source_url": "https://www.adobe.com/in/careers",
        "source_name": "Adobe University Careers",
        "publication_date": get_iso_date(-14),
        "last_verified_date": get_iso_date(-2),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Official corporate university relations initiative verified.",
        "opportunity_status": "Active",
        "stipend_or_reward": "Full tuition assistance + Summer Internship interview + Mentorship",
        "tags": ["Diversity", "Women in Tech", "Scholarship", "Internship"],
        "is_sample": True
    },
    {
        "id": "opp-razorpay-frontend-intern",
        "title": "Frontend Engineering Intern (React & TypeScript)",
        "organization": "Razorpay",
        "category": "Internship",
        "description": "Work with the Checkout and Merchant Dashboard teams to build seamless, high-performance financial interfaces handling millions of transactions every day.",
        "required_skills": ["React", "JavaScript", "HTML", "CSS", "Git"],
        "preferred_skills": ["TypeScript", "Tailwind CSS", "Redux", "Web Performance"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "BCA", "B.Sc", "MCA"],
            "eligible_academic_years": ["2nd Year", "3rd Year", "4th Year"],
            "min_cgpa": 6.5,
            "eligible_branches": ["All"],
            "other_requirements": "Strong portfolio of frontend web applications or open source contributions."
        },
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9166,
        "longitude": 77.6101,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-8),
        "deadline": get_iso_date(7),  # 7 days remaining (Yellow)
        "official_url": "https://razorpay.com/jobs",
        "source_url": "https://razorpay.com/jobs/intern-frontend",
        "source_name": "Razorpay Career Portal",
        "publication_date": get_iso_date(-8),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 95,
        "verification_notes": "Direct listing on Razorpay Greenhouse board.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹50,000 / month + MacBook Pro for internship",
        "tags": ["FinTech", "Frontend", "React", "High Impact"],
        "is_sample": True
    },
    {
        "id": "opp-ethglobal-hackathon",
        "title": "ETHGlobal Web3 & Decentralized Systems Hackathon",
        "organization": "ETHGlobal",
        "category": "Hackathon",
        "description": "ETHGlobal brings together thousands of developers from around the world to build the next generation of decentralized applications, protocols, and developer tooling.",
        "required_skills": ["JavaScript", "React", "Git", "Problem Solving"],
        "preferred_skills": ["Solidity", "Smart Contracts", "Ethers.js", "Web3"],
        "eligibility_criteria": {
            "eligible_degrees": ["All"],
            "eligible_academic_years": ["All"],
            "min_cgpa": None,
            "eligible_branches": ["All"],
            "other_requirements": "Solo or teams up to 5 members. Beginners welcome; workshops provided."
        },
        "location": "Global / Remote",
        "city": "Hyderabad",
        "country": "India",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-12),
        "deadline": get_iso_date(14), # 14 days (Yellow / Green boundary)
        "official_url": "https://ethglobal.com",
        "source_url": "https://ethglobal.com/events",
        "source_name": "ETHGlobal Events Feed",
        "publication_date": get_iso_date(-12),
        "last_verified_date": get_iso_date(-2),
        "verification_status": "Verified Source",
        "trust_score": 94,
        "verification_notes": "Official community hackathon verified through ETHGlobal verified registry.",
        "opportunity_status": "Active",
        "stipend_or_reward": "$250,000 in total prizes across tracks",
        "tags": ["Hackathon", "Web3", "Decentralized", "Global Prizes"],
        "is_sample": True
    },
    {
        "id": "opp-iisc-summer-research",
        "title": "IISc Summer Research Fellowship in Computer Science",
        "organization": "Indian Institute of Science (IISc)",
        "category": "Research Program",
        "description": "A prestigious two-month summer research fellowship at the Department of Computer Science and Automation (CSA), IISc Bengaluru. Fellows conduct research under leading faculty in AI, Algorithms, and Systems.",
        "required_skills": ["Python", "Algorithms", "Mathematics", "Data Structures"],
        "preferred_skills": ["C++", "PyTorch", "Research Writing", "Linear Algebra"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "M.Tech", "M.Sc"],
            "eligible_academic_years": ["2nd Year", "3rd Year", "Masters"],
            "min_cgpa": 8.5,
            "eligible_branches": ["Computer Science and Engineering", "Information Technology", "Mathematics", "Electrical Engineering"],
            "other_requirements": "Top 10% class rank in academic year."
        },
        "location": "Bengaluru, Karnataka",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 13.0219,
        "longitude": 77.5671,
        "work_mode": "On-site",
        "opening_date": get_iso_date(-18),
        "deadline": get_iso_date(5),  # 5 days (Yellow)
        "official_url": "https://csa.iisc.ac.in",
        "source_url": "https://csa.iisc.ac.in/summer-internship",
        "source_name": "IISc CSA Official Announcements",
        "publication_date": get_iso_date(-18),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Premier institute domain (.ac.in) verified with signed faculty notification.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹15,000 / month + Campus accommodation and library access",
        "tags": ["Research", "Premier Institute", "Publication Opportunity", "IISc"],
        "is_sample": True
    },
    {
        "id": "opp-genai-bootcamp-workshop",
        "title": "Full-Stack Generative AI & Agentic Systems Workshop",
        "organization": "IIT Madras Research Park & NASSCOM",
        "category": "Workshop",
        "description": "An intensive hands-on 3-day deep dive workshop on building production-grade agentic AI systems, RAG pipelines, fine-tuning open-weights models, and deploying on Kubernetes.",
        "required_skills": ["Python", "API Basics"],
        "preferred_skills": ["FastAPI", "React", "Vector Databases", "Docker"],
        "eligibility_criteria": {
            "eligible_degrees": ["All"],
            "eligible_academic_years": ["All"],
            "min_cgpa": None,
            "eligible_branches": ["All"],
            "other_requirements": "Open to all students and recent graduates with basic Python familiarity."
        },
        "location": "Chennai / Virtual Live Stream",
        "city": "Chennai",
        "country": "India",
        "latitude": 12.9915,
        "longitude": 80.2337,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-5),
        "deadline": get_iso_date(9),  # 9 days (Yellow)
        "official_url": "https://respark.iitm.ac.in",
        "source_url": "https://respark.iitm.ac.in/events/genai-2026",
        "source_name": "IITM Research Park Events",
        "publication_date": get_iso_date(-5),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 96,
        "verification_notes": "Direct event listing on university tech incubator portal.",
        "opportunity_status": "Active",
        "stipend_or_reward": "Free for students + Verified Industry Certificate + Cloud Credits",
        "tags": ["Workshop", "GenAI", "Hands-on", "IIT Madras"],
        "is_sample": True
    },
    {
        "id": "opp-goldman-sachs-grad",
        "title": "Engineering Campus Associate 2026",
        "organization": "Goldman Sachs",
        "category": "Entry-level Job",
        "description": "Goldman Sachs Engineering develops solutions to complex problems in financial software. As an Associate, you will build algorithmic trading pipelines, enterprise data infrastructure, or resilient web banking services.",
        "required_skills": ["Java", "Python", "Data Structures", "Algorithms", "SQL"],
        "preferred_skills": ["Distributed Systems", "Spring Boot", "Kafka", "Linux"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "MCA", "M.Tech"],
            "eligible_academic_years": ["4th Year", "Masters"],
            "min_cgpa": 7.5,
            "eligible_branches": ["Computer Science and Engineering", "Information Technology", "Electrical Engineering", "Mathematics"],
            "other_requirements": "Final year students graduating in 2026."
        },
        "location": "Bengaluru / Hyderabad",
        "city": "Hyderabad",
        "country": "India",
        "latitude": 17.4375,
        "longitude": 78.3619,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-16),
        "deadline": get_iso_date(19), # 19 days (Green)
        "official_url": "https://www.goldmansachs.com/careers/students/",
        "source_url": "https://www.goldmansachs.com/careers",
        "source_name": "Goldman Sachs Official Student Careers",
        "publication_date": get_iso_date(-16),
        "last_verified_date": get_iso_date(-3),
        "verification_status": "Verified Source",
        "trust_score": 98,
        "verification_notes": "Official institutional hiring calendar listing.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹24 LPA - ₹30 LPA CTC + Sign-on bonus",
        "tags": ["Full-Time", "FinTech", "High CTC", "New Grad"],
        "is_sample": True
    },
    {
        "id": "opp-gcp-cert-scholarship",
        "title": "Google Cloud Associate Cloud Engineer Certification Grant",
        "organization": "Google Cloud & GDG Campus",
        "category": "Certification",
        "description": "Sponsored 100% exam voucher and Qwiklabs training access for undergraduate students to get officially certified as a Google Cloud Associate Cloud Engineer.",
        "required_skills": ["Cloud Computing", "Linux", "Networking Basics"],
        "preferred_skills": ["GCP", "Kubernetes", "IAM", "Python"],
        "eligibility_criteria": {
            "eligible_degrees": ["All"],
            "eligible_academic_years": ["2nd Year", "3rd Year", "4th Year", "Masters"],
            "min_cgpa": None,
            "eligible_branches": ["All"],
            "other_requirements": "Complete 4 prerequisite Google Cloud skill badges before deadline."
        },
        "location": "Online / Pan-India",
        "city": "Pune",
        "country": "India",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-9),
        "deadline": get_iso_date(11), # 11 days (Yellow)
        "official_url": "https://cloud.google.com/certification/cloud-engineer",
        "source_url": "https://developers.google.com/community/gdsc",
        "source_name": "Google Developer Student Clubs",
        "publication_date": get_iso_date(-9),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 97,
        "verification_notes": "Verified GDSC program sponsored by Google Cloud India team.",
        "opportunity_status": "Active",
        "stipend_or_reward": "100% Exam Voucher ($125 value) + Google Swag",
        "tags": ["Certification", "Google Cloud", "Free Voucher", "Career Boost"],
        "is_sample": True
    },
    {
        "id": "opp-tata-merit-scholarship",
        "title": "Tata Trusts Merit Scholarship for STEM 2026",
        "organization": "Tata Trusts",
        "category": "Scholarship",
        "description": "Recognizing young minds with exceptional academic promise in Science, Technology, Engineering, and Mathematics to foster indigenous technical innovation in India.",
        "required_skills": ["Problem Solving", "Academic Dedication"],
        "preferred_skills": ["Research Aptitude"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "M.Tech"],
            "eligible_academic_years": ["2nd Year", "3rd Year", "4th Year"],
            "min_cgpa": 8.0,
            "eligible_branches": ["All STEM Branches"],
            "other_requirements": "Permanent resident of India. Verified marks sheets of prior semesters."
        },
        "location": "Mumbai, Maharashtra",
        "city": "Mumbai",
        "country": "India",
        "latitude": 18.9298,
        "longitude": 72.8335,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-21),
        "deadline": get_iso_date(15), # 15 days (Green)
        "official_url": "https://www.tatatrusts.org/our-work/individual-grants-education/scholarships",
        "source_url": "https://www.tatatrusts.org",
        "source_name": "Tata Trusts Education Grants Portal",
        "publication_date": get_iso_date(-21),
        "last_verified_date": get_iso_date(-4),
        "verification_status": "Verified Source",
        "trust_score": 98,
        "verification_notes": "Verified institutional philanthropy grant with direct application flow.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹1,00,000 financial grant towards annual college fees",
        "tags": ["Scholarship", "Tata Trusts", "Merit", "Financial Aid"],
        "is_sample": True
    },
    {
        "id": "opp-nasa-space-apps",
        "title": "NASA International Space Apps Challenge 2026",
        "organization": "NASA & Open Data Program",
        "category": "Competition",
        "description": "NASA's Space Apps is the largest annual global hackathon. Over 48 hours, coders, scientists, designers, storytellers, makers, and technologists engage with NASA's free and open data to address real-world problems on Earth and in space.",
        "required_skills": ["Problem Solving", "Python", "Data Analysis"],
        "preferred_skills": ["Machine Learning", "GIS", "Web Development", "UI/UX"],
        "eligibility_criteria": {
            "eligible_degrees": ["All"],
            "eligible_academic_years": ["All"],
            "min_cgpa": None,
            "eligible_branches": ["All"],
            "other_requirements": "Open to all students, beginners and experts alike."
        },
        "location": "Mumbai & Virtual Global",
        "city": "Mumbai",
        "country": "India",
        "latitude": 19.1334,
        "longitude": 72.9133,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-11),
        "deadline": get_iso_date(6),  # 6 days (Yellow)
        "official_url": "https://www.spaceappschallenge.org",
        "source_url": "https://www.spaceappschallenge.org/locations",
        "source_name": "NASA Space Apps Global Operations",
        "publication_date": get_iso_date(-11),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Official NASA open science project certified domain.",
        "opportunity_status": "Active",
        "stipend_or_reward": "NASA Global Winner recognition + Space Center invite",
        "tags": ["NASA", "Space", "Competition", "Global"],
        "is_sample": True
    },
    {
        "id": "opp-cern-summer-student",
        "title": "CERN Summer Student Programme 2026",
        "organization": "European Organization for Nuclear Research (CERN)",
        "category": "Research Program",
        "description": "Spend 8 to 13 weeks at CERN in Geneva, Switzerland working on an advanced technical project within an experimental or engineering team, attending world-class physics and computing lectures.",
        "required_skills": ["Python", "C++", "Linux", "Data Analysis"],
        "preferred_skills": ["High Performance Computing", "Distributed Systems", "ROOT"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "M.Tech", "M.Sc"],
            "eligible_academic_years": ["3rd Year", "4th Year", "Masters"],
            "min_cgpa": 8.0,
            "eligible_branches": ["Computer Science and Engineering", "Physics", "Mathematics", "Electrical Engineering"],
            "other_requirements": "Must have completed at least 3 years of full-time studies at university level."
        },
        "location": "Geneva / Hybrid",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9784,
        "longitude": 77.6408,
        "work_mode": "On-site",
        "opening_date": get_iso_date(-28),
        "deadline": get_iso_date(1),  # Urgent: 1 day (Red)
        "official_url": "https://careers.cern/summer-student-programme",
        "source_url": "https://careers.cern",
        "source_name": "CERN International Human Resources",
        "publication_date": get_iso_date(-28),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 100,
        "verification_notes": "Official international research lab authenticated recruitment portal.",
        "opportunity_status": "Closing Soon",
        "stipend_or_reward": "90 CHF / day subsistence allowance + Travel reimbursement",
        "tags": ["Research", "CERN", "International", "Physics & Computing"],
        "is_sample": True
    },
    {
        "id": "unstop-polycab-campus-hiring",
        "title": "Polycab Graduate Campus Hiring 2026 - 2027 (PGT Sales & Tech)",
        "organization": "Polycab India Limited",
        "category": "Entry-level Job",
        "description": "Polycab India invites ambitious graduating engineers and graduates to join the prestigious Post Graduate Trainee (PGT) Program. Selected candidates gain cross-functional exposure across sales territory management, electrical solutions architecture, and customer relationship management with direct executive mentorship.",
        "required_skills": ["Sales Territory Management", "Relationship Management", "Customer orientation", "Communication"],
        "preferred_skills": ["Business Analysis", "Negotiation", "B2B Strategy"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "BBA", "B.Com", "BCA", "All"],
            "eligible_academic_years": ["4th Year", "Masters"],
            "min_cgpa": 6.0,
            "eligible_branches": ["Electrical and Electronics", "Computer Science and Engineering", "All Branches"],
            "other_requirements": "Final year graduating students (2026-2027 cohort). Strong verbal and written communication."
        },
        "location": "Mumbai / Pan-India",
        "city": "Mumbai",
        "country": "India",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-7),
        "deadline": get_iso_date(16),
        "official_url": "https://www.polycab.com/careers",
        "source_url": "https://unstop.com/jobs/crp-campus-hiring-pgt-sales-2027-aarambh-polycab-1755458",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-7),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 98,
        "verification_notes": "Official corporate hiring drive listed on Unstop with verified career portal at polycab.com.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹6.5 LPA - ₹8.5 LPA CTC + Performance Incentive",
        "tags": ["Unstop", "Full-Time", "Core Engineering", "PGT", "Campus Hiring"],
        "is_sample": True
    },
    {
        "id": "unstop-learntricks-python-intern",
        "title": "Python & Cloud Engineering Internship",
        "organization": "Learntricks Edutech",
        "category": "Internship",
        "description": "Hands-on engineering internship working with Python, RESTful API design, PostgreSQL, and cloud deployments. You will collaborate with senior developers on building interactive education technology modules and microservices.",
        "required_skills": ["Python", "Backend development", "JavaScript", "HTML", "CSS"],
        "preferred_skills": ["FastAPI", "Docker", "PostgreSQL", "Git"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "BCA", "B.Sc", "MCA"],
            "eligible_academic_years": ["2nd Year", "3rd Year", "4th Year"],
            "min_cgpa": None,
            "eligible_branches": ["Computer Science and Engineering", "Information Technology", "All"],
            "other_requirements": "Open to all students with demonstrable Python and web development project repositories."
        },
        "location": "Bengaluru / Remote",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-5),
        "deadline": get_iso_date(12),
        "official_url": "https://learntricks.com",
        "source_url": "https://unstop.com/internships/python-internship-unstop-tech-fair-2025-learntricks-edutech-1765719",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-5),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 96,
        "verification_notes": "Verified partner organization through Unstop Tech Fair with active official company website.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹20,000 / month + Internship Certificate",
        "tags": ["Unstop", "Internship", "Python", "Remote", "EdTech"],
        "is_sample": True
    },
    {
        "id": "unstop-flipkart-grid-7",
        "title": "Flipkart GRiD 7.0 - Engineering Campus Challenge",
        "organization": "Flipkart",
        "category": "Hackathon",
        "description": "Flipkart GRiD is Flipkart's flagship national engineering challenge. Across multiple live coding and prototyping tracks (E-Commerce Tech, GenAI & Robotics), students solve real-world industry scale problems with lucrative cash prizes and pre-placement interviews.",
        "required_skills": ["Problem Solving", "Data Structures", "Algorithms", "Python", "Java"],
        "preferred_skills": ["Machine Learning", "System Design", "React", "Distributed Systems"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "M.Tech", "Dual Degree"],
            "eligible_academic_years": ["2nd Year", "3rd Year", "4th Year"],
            "min_cgpa": None,
            "eligible_branches": ["All Engineering Branches"],
            "other_requirements": "Teams of 2 to 3 students from the same accredited engineering college."
        },
        "location": "Bengaluru / Online",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9352,
        "longitude": 77.6245,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-12),
        "deadline": get_iso_date(10),
        "official_url": "https://www.flipkartcareers.com",
        "source_url": "https://unstop.com/hackathons/flipkart-grid-engineering-campus-challenge",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-12),
        "last_verified_date": get_iso_date(-2),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Official flagship enterprise competition verified via Flipkart and Unstop corporate registry.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹5,25,000 Total Cash Pool + Pre-Placement Interviews (PPI) for SDE roles (₹32 LPA CTC)",
        "tags": ["Unstop", "Flipkart", "Hackathon", "High CTC", "PPI", "National"],
        "is_sample": True
    },
    {
        "id": "unstop-amber-scholarship",
        "title": "AmberScholar Global Undergraduate Scholarship 2026",
        "organization": "Amber (AmberStudent)",
        "category": "Scholarship",
        "description": "AmberScholar is a merit-based initiative designed to reward and support bright, ambitious students pursuing higher education. Recipients receive direct tuition fee subsidies and access to international student community mentorship.",
        "required_skills": ["Academic Excellence", "Leadership", "Communication Skills"],
        "preferred_skills": ["Statement of Purpose Writing", "Extracurricular Achievements"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "BBA", "BCA", "All"],
            "eligible_academic_years": ["1st Year", "2nd Year", "3rd Year", "4th Year", "Masters"],
            "min_cgpa": 7.0,
            "eligible_branches": ["All Branches"],
            "other_requirements": "Enrolled in a recognized college or university in India, UK, USA, or Australia."
        },
        "location": "Global / Remote",
        "city": "Pune",
        "country": "India",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "work_mode": "Remote",
        "opening_date": get_iso_date(-15),
        "deadline": get_iso_date(20),
        "official_url": "https://amberstudent.com/careers",
        "source_url": "https://unstop.com/scholarships/amberscholar-scholarship-amber-787306",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-15),
        "last_verified_date": get_iso_date(-2),
        "verification_status": "Verified Source",
        "trust_score": 97,
        "verification_notes": "Global student accommodation provider scholarship verified on Amber career portal.",
        "opportunity_status": "Active",
        "stipend_or_reward": "£10,000 ($12,500) Scholarship Grants + Housing Support",
        "tags": ["Unstop", "Scholarship", "Global", "Undergraduate", "Tuition Grant"],
        "is_sample": True
    },
    {
        "id": "unstop-tata-imagination-challenge",
        "title": "Tata Imagination Challenge 2026 - Student Innovation Track",
        "organization": "Tata Sons & Tata Group",
        "category": "Competition",
        "description": "The Tata Imagination Challenge is among India's largest student idea competitions. It invites undergrad and postgrad students to showcase curiosity, problem-solving, and visionary leadership to address national challenges.",
        "required_skills": ["Problem Solving", "Strategic Thinking", "Communication", "Innovation"],
        "preferred_skills": ["Product Design", "Sustainability Analysis", "Business Modeling"],
        "eligibility_criteria": {
            "eligible_degrees": ["All Degrees"],
            "eligible_academic_years": ["All Academic Years"],
            "min_cgpa": None,
            "eligible_branches": ["All Disciplines"],
            "other_requirements": "Open to all students enrolled in any higher educational institution in India."
        },
        "location": "Mumbai / Virtual",
        "city": "Mumbai",
        "country": "India",
        "latitude": 18.9298,
        "longitude": 72.8335,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-14),
        "deadline": get_iso_date(14),
        "official_url": "https://www.tata.com/careers",
        "source_url": "https://unstop.com/competitions/tata-imagination-challenge",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-14),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 100,
        "verification_notes": "Premier Tata Group institutional national competition verified through official portal tata.com.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹2,00,000 Cash Prize for 13 Winners + Tata Leader Mentorship & TAS Fast-Track",
        "tags": ["Unstop", "Tata", "National", "Innovation", "Leadership", "Prestige"],
        "is_sample": True
    },
    {
        "id": "unstop-walmart-codehers",
        "title": "Walmart CodeHers India 2026 (Software Development Hiring Challenge)",
        "organization": "Walmart Global Tech",
        "category": "Hackathon",
        "description": "Walmart CodeHers is India's premier coding challenge for female engineering students. Top participants win cash rewards, certificates, and direct interview opportunities for Software Development Engineer (SDE) roles at Walmart Global Tech India.",
        "required_skills": ["Data Structures", "Algorithms", "Java", "C++", "Python"],
        "preferred_skills": ["Problem Solving", "System Architecture", "Object Oriented Programming"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "M.Tech", "MCA", "Dual Degree"],
            "eligible_academic_years": ["3rd Year", "4th Year"],
            "min_cgpa": 7.0,
            "eligible_branches": ["Computer Science and Engineering", "Information Technology", "Circuital Branches"],
            "other_requirements": "Female engineering students graduating in 2026 or 2027."
        },
        "location": "Bengaluru / Chennai",
        "city": "Bengaluru",
        "country": "India",
        "latitude": 12.9166,
        "longitude": 77.6101,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-10),
        "deadline": get_iso_date(11),
        "official_url": "https://careers.walmart.com",
        "source_url": "https://unstop.com/hackathons/walmart-codehers",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-10),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Official Walmart Global Tech campus recruitment initiative verified at careers.walmart.com.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹23 LPA - ₹28 LPA SDE Full-Time Offer / ₹1,00,000 per month Summer Internship + ₹1.5L Cash Prize",
        "tags": ["Unstop", "Walmart", "Diversity", "High CTC", "SDE", "Women In Tech"],
        "is_sample": True
    },
    {
        "id": "unstop-bannari-iot-hackathon",
        "title": "National IoT & Applied Smart Systems Hackathon",
        "organization": "Bannari Amman Institute of Technology",
        "category": "Hackathon",
        "description": "National level hackathon encouraging collegiate developers to build real-world IoT sensors, embedded telemetry, and cloud dashboard integrations to tackle industrial and smart agricultural problems.",
        "required_skills": ["IoT", "Python", "C++", "Hardware Interfacing"],
        "preferred_skills": ["MQTT", "AWS IoT", "React", "Raspberry Pi"],
        "eligibility_criteria": {
            "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "Diploma"],
            "eligible_academic_years": ["1st Year", "2nd Year", "3rd Year", "4th Year"],
            "min_cgpa": None,
            "eligible_branches": ["All Engineering Branches"],
            "other_requirements": "Open to student teams of 2 to 4 members."
        },
        "location": "Sathyamangalam, Tamil Nadu",
        "city": "Coimbatore",
        "country": "India",
        "latitude": 11.5034,
        "longitude": 77.2442,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-6),
        "deadline": get_iso_date(8),
        "official_url": "https://www.bitsathy.ac.in",
        "source_url": "https://unstop.com/hackathons/iot-hackathon-v-prayukti25-bannari-amman-institute-of-technology-1369976",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-6),
        "last_verified_date": get_iso_date(-1),
        "verification_status": "Verified Source",
        "trust_score": 96,
        "verification_notes": "Autonomous engineering institution certified technical event verified via bitsathy.ac.in.",
        "opportunity_status": "Active",
        "stipend_or_reward": "₹75,000 Cash Prize Pool + Hardware Incubation Support",
        "tags": ["Unstop", "Hackathon", "IoT", "Embedded", "Smart Systems"],
        "is_sample": True
    },
    {
        "id": "unstop-loreal-brandstorm",
        "title": "L'Oréal Brandstorm 2026 - Global Tech & Innovation Mission",
        "organization": "L'Oréal",
        "category": "Competition",
        "description": "L'Oréal Brandstorm is one of the world's most renowned innovation competitions for students. Participants crack disruption tracks combining AI beauty-tech, sustainable materials, and personalized consumer experiences with international finals in Paris.",
        "required_skills": ["Innovation", "Product Strategy", "Team Collaboration", "Presentation"],
        "preferred_skills": ["AI/ML Applications", "UI/UX Prototyping", "Digital Marketing"],
        "eligibility_criteria": {
            "eligible_degrees": ["All Undergrad & Postgrad Degrees"],
            "eligible_academic_years": ["All Academic Years"],
            "min_cgpa": None,
            "eligible_branches": ["All Branches"],
            "other_requirements": "Teams of 3 students from any recognized university."
        },
        "location": "Mumbai / Paris / Hybrid",
        "city": "Mumbai",
        "country": "India",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "work_mode": "Hybrid",
        "opening_date": get_iso_date(-18),
        "deadline": get_iso_date(18),
        "official_url": "https://careers.loreal.com",
        "source_url": "https://unstop.com/competitions/loreal-brandstorm",
        "source_name": "Unstop (unstop.com)",
        "publication_date": get_iso_date(-18),
        "last_verified_date": get_iso_date(-2),
        "verification_status": "Verified Source",
        "trust_score": 99,
        "verification_notes": "Official multinational beauty-tech company challenge verified on careers.loreal.com.",
        "opportunity_status": "Active",
        "stipend_or_reward": "All-expenses paid trip to Paris Finals + 3-month Intrapreneurship at Station F Paris",
        "tags": ["Unstop", "L'Oréal", "Global", "Innovation", "Tech & Beauty", "Paris"],
        "is_sample": True
    }
]
